#include <stdio.h>
#include <stdlib.h>
#include <string.h> // For memset and strncpy
#include <assert.h>

# include <unistd.h>
# include <pwd.h>
# define MAX_PATH FILENAME_MAX

#include "sgx_urts.h"
#include "App.h"
#include "Enclave_u.h" // Generated by the EDL

// From the Included Folder
#include "ScheduleData.h"
#include "cJSON.h"

sgx_enclave_id_t global_eid = 0;



/* Encalve code from the Cxx11 sample */

typedef struct _sgx_errlist_t {
    sgx_status_t err;
    const char *msg;
    const char *sug; /* Suggestion */
} sgx_errlist_t;

/* Error code returned by sgx_create_enclave */
static sgx_errlist_t sgx_errlist[] = {
    {
        SGX_ERROR_UNEXPECTED,
        "Unexpected error occurred.",
        NULL
    },
    {
        SGX_ERROR_INVALID_PARAMETER,
        "Invalid parameter.",
        NULL
    },
    {
        SGX_ERROR_OUT_OF_MEMORY,
        "Out of memory.",
        NULL
    },
    {
        SGX_ERROR_ENCLAVE_LOST,
        "Power transition occurred.",
        "Please refer to the sample \"PowerTransition\" for details."
    },
    {
        SGX_ERROR_INVALID_ENCLAVE,
        "Invalid enclave image.",
        NULL
    },
    {
        SGX_ERROR_INVALID_ENCLAVE_ID,
        "Invalid enclave identification.",
        NULL
    },
    {
        SGX_ERROR_INVALID_SIGNATURE,
        "Invalid enclave signature.",
        NULL
    },
    {
        SGX_ERROR_OUT_OF_EPC,
        "Out of EPC memory.",
        NULL
    },
    {
        SGX_ERROR_NO_DEVICE,
        "Invalid SGX device.",
        "Please make sure SGX module is enabled in the BIOS, and install SGX driver afterwards."
    },
    {
        SGX_ERROR_MEMORY_MAP_CONFLICT,
        "Memory map conflicted.",
        NULL
    },
    {
        SGX_ERROR_INVALID_METADATA,
        "Invalid enclave metadata.",
        NULL
    },
    {
        SGX_ERROR_DEVICE_BUSY,
        "SGX device was busy.",
        NULL
    },
    {
        SGX_ERROR_INVALID_VERSION,
        "Enclave version was invalid.",
        NULL
    },
    {
        SGX_ERROR_INVALID_ATTRIBUTE,
        "Enclave was not authorized.",
        NULL
    },
    {
        SGX_ERROR_ENCLAVE_FILE_ACCESS,
        "Can't open enclave file.",
        NULL
    },
    {
        SGX_ERROR_MEMORY_MAP_FAILURE,
        "Failed to reserve memory for the enclave.",
        NULL
    },
};

/* Check error conditions for loading enclave */
void print_error_message(sgx_status_t ret)
{
    size_t idx = 0;
    size_t ttl = sizeof sgx_errlist/sizeof sgx_errlist[0];

    for (idx = 0; idx < ttl; idx++) {
        if(ret == sgx_errlist[idx].err) {
            if(NULL != sgx_errlist[idx].sug)
                printf("Info: %s\n", sgx_errlist[idx].sug);
            printf("Error: %s\n", sgx_errlist[idx].msg);
            break;
        }
    }
    
    if (idx == ttl)
    	printf("Error code is 0x%X. Please refer to the \"Intel SGX SDK Developer Reference\" for more details.\n", ret);
}

// Initialize the enclave:
int initialize_enclave(void)
{
    sgx_status_t ret = SGX_ERROR_UNEXPECTED;
    
    /* Call sgx_create_enclave to initialize an enclave instance */
    /* Debug Support: set 2nd parameter to 1 */
    ret = sgx_create_enclave(ENCLAVE_FILENAME, SGX_DEBUG_FLAG, NULL, NULL, &global_eid, NULL);
    if (ret != SGX_SUCCESS) {
        print_error_message(ret);
        return -1;
    }

    return 0;
}



/* OCalls implementations */

// Simple printf for debug
void ocall_print_string(const char *str)
{
    printf("%s", str);
}



/* Helper functions */

// Returns the string with the content the file
char* read_file_to_string(const char* filename) {

    FILE *f = fopen(filename, "r");
    if (f == NULL) {
        printf("Error: Could not open %s\n", filename);
        return NULL;
    }

    // Determine file size
    fseek(f, 0, SEEK_END); // SEEK_END is relative to the end-of-file
    long fsize = ftell(f);
    fseek(f, 0, SEEK_SET); // SEEK_SET is relative to the start-of-file

    printf("1 - [App] The size of the file %s is %ld bytes\n", filename,fsize);

    // Allocate memory (fsize + 1 for the null terminator)
    char *string = (char *)malloc(fsize + 1);
    if (string == NULL) {
        fclose(f);
        return NULL;
    }

    // Read and close
    fread(string, fsize, 1, f);
    fclose(f);
    string[fsize] = '\0'; 

    printf("2 - [App] Total memory allocated (including null terminator): %ld bytes\n", fsize + 1);

    return string;
}

// Parses the file with the schedules and sends the array to the Enclave
void parse_and_send_schedule(sgx_enclave_id_t eid, const char* input_file) {

    // Safety check
    if (input_file == NULL) {
        printf("[App Error] Failed to load file\n");
        return;
    }

    cJSON *json = cJSON_Parse(input_file);

    if (json == NULL) {
        printf("[App Error] Failed to parse JSON\n");
        return;
    }

    // Create a temporary array to hold the data
    schedule_entry_t flat_schedule[200];
    uint32_t total_entries = 0;

    //Using class_var since class is reserved keyword
    cJSON *class_var = NULL;

    // Loop trhough each class
    cJSON_ArrayForEach(class_var, json) {
        uint32_t code = (uint32_t)atoi(class_var->string);
        cJSON *acronym = cJSON_GetObjectItem(class_var, "acronym");
        cJSON *classes = cJSON_GetObjectItem(class_var, "classes");

        cJSON *cls = NULL;
        // Loop through the classes inside this course
        cJSON_ArrayForEach(cls, classes) {

            if (total_entries >= 200) {
                printf("[App Error] Warning: Max classes reached.\n");
                break;
            }

            schedule_entry_t *entry = &flat_schedule[total_entries];
            
            // Zero out the struct for padding
           memset(entry, 0, sizeof(schedule_entry_t));

            // Course Code & Acronym
            entry->course_code = code;
            if (acronym && acronym->valuestring) {
                strncpy(entry->acronym, acronym->valuestring, 7);
            }
            
            // Class ID
            cJSON *id = cJSON_GetObjectItem(cls, "id");
            if (id && id->valuestring) {
                strncpy(entry->class_id, id->valuestring, 7);
            } else {
                strncpy(entry->class_id, "UNK", 7);
            }
            
            // Room
            cJSON *room = cJSON_GetObjectItem(cls, "room");
            if (room && room->valuestring) {
                strncpy(entry->room, room->valuestring, 8);
            } else {
                strncpy(entry->room, "TBD", 8);
            }

            // Day 
            cJSON *day = cJSON_GetObjectItem(cls, "day");
            if (day && day->valuestring) {
                entry->day = (uint8_t)atoi(day->valuestring);
            }

            // Time Interval
            cJSON *time = cJSON_GetObjectItem(cls, "time_interval");
            if (time && time->valuestring) {
                strncpy(entry->time_interval, time->valuestring, 15);
            } else {
                strncpy(entry->time_interval, "TBD", 15);
            }

            total_entries++;
        }
    }

    if (total_entries > 0) {

        // Send data to enclave
        sgx_status_t status = ecall_load_schedule(eid, flat_schedule, total_entries);
        
        if (status == SGX_SUCCESS) {
            printf("3 - [App] Successfully passed %u classes to the Enclave.\n", total_entries);
        } else {
            printf("[App Error] ECALL failed with code: %x\n", status);
        }
    } else {
        printf("[App Error] No classes found in JSON.\n");
    }

    // Free the JSON memory
    cJSON_Delete(json);

}

// Parses the file with the classes and sends the array to the Enclave
void parse_and_send_class(sgx_enclave_id_t eid, const char* input_file) {
    // Safety check
    if (input_file == NULL) {
        printf("[App Error] Failed to load file\n");
        return;
    }
}


/* Application entry */

int SGX_CDECL main(int argc, char *argv[])
{
    // To avoid compilation errors
    (void)(argc);
    (void)(argv);

    /* Initialize the enclave */
    if(initialize_enclave() < 0){
        printf("[App Error] Unable to start enclave");
        printf("Enter a character before exit ...\n");
        getchar();
        return -1; 
    }

    int choice = -1; 
    while (choice != 0) {
        printf("\n===================================================\n");
        printf("      SGX Secure Attendance System - Main Menu     \n");
        printf("===================================================\n");
        printf("1 - Calculate weekly attendance per class (Load Map)\n");
        printf("2 - Calculate student attendance frequency (Graphic)\n");
        printf("0 - Exit Application\n");
        printf("===================================================\n");
        printf("Enter your choice: ");

        // Read the user input
        if (scanf("%d", &choice) != 1) {
            // Verify it is a valid number
            while (getchar() != '\n'); 
            printf("[App] Invalid input. Please enter a number.\n");
            continue;
        }

        printf("\n"); // for clean formatting

        switch (choice) {
            case 1:{
                printf("[App] Option 1 Selected: Calculating weekly attendance...\n");

                // Read the input files that are public
                char* schedule_data = read_file_to_string("schedules.json");
                //char* classes_data = read_file_to_string("classes.json");

                // Parse them and send them to the enclave
                parse_and_send_schedule(global_eid, schedule_data);
                // parse_and_send_class(global_eid, classes_data);

                // Maybe an ecall to warn the enclave to start processing?


                break;}

            case 2:{
                printf("[App] Option 2 Selected: Calculating frequency graphic...\n");
                
                break;}

            case 0:{
                printf("[App] Exiting the application. Destroying Enclave...\n");

                /* Destroy the enclave */
                sgx_destroy_enclave(global_eid);

                break;}

            default:{
                printf("[App] Unknown choice (%d). Please select 1, 2, or 0.\n", choice);
                break;}
        }
    }
    
    printf("Info: Enclave successfully returned.\n");

    return 0;
}