#include <stdio.h>
#include <stdlib.h>
#include <string.h> // For memset and strncpy
#include <assert.h>

# include <unistd.h>
# include <pwd.h>
# define MAX_PATH FILENAME_MAX

#include "sgx_urts.h"
#include "App.h"
#include "Enclave_u.h" // Generated by the EDL

// From the Included Folder
#include "ScheduleData.h"
#include "cJSON.h"

sgx_enclave_id_t global_eid = 0;



/* Encalve code from the Cxx11 sample */

typedef struct _sgx_errlist_t {
    sgx_status_t err;
    const char *msg;
    const char *sug; /* Suggestion */
} sgx_errlist_t;

/* Error code returned by sgx_create_enclave */
static sgx_errlist_t sgx_errlist[] = {
    {
        SGX_ERROR_UNEXPECTED,
        "Unexpected error occurred.",
        NULL
    },
    {
        SGX_ERROR_INVALID_PARAMETER,
        "Invalid parameter.",
        NULL
    },
    {
        SGX_ERROR_OUT_OF_MEMORY,
        "Out of memory.",
        NULL
    },
    {
        SGX_ERROR_ENCLAVE_LOST,
        "Power transition occurred.",
        "Please refer to the sample \"PowerTransition\" for details."
    },
    {
        SGX_ERROR_INVALID_ENCLAVE,
        "Invalid enclave image.",
        NULL
    },
    {
        SGX_ERROR_INVALID_ENCLAVE_ID,
        "Invalid enclave identification.",
        NULL
    },
    {
        SGX_ERROR_INVALID_SIGNATURE,
        "Invalid enclave signature.",
        NULL
    },
    {
        SGX_ERROR_OUT_OF_EPC,
        "Out of EPC memory.",
        NULL
    },
    {
        SGX_ERROR_NO_DEVICE,
        "Invalid SGX device.",
        "Please make sure SGX module is enabled in the BIOS, and install SGX driver afterwards."
    },
    {
        SGX_ERROR_MEMORY_MAP_CONFLICT,
        "Memory map conflicted.",
        NULL
    },
    {
        SGX_ERROR_INVALID_METADATA,
        "Invalid enclave metadata.",
        NULL
    },
    {
        SGX_ERROR_DEVICE_BUSY,
        "SGX device was busy.",
        NULL
    },
    {
        SGX_ERROR_INVALID_VERSION,
        "Enclave version was invalid.",
        NULL
    },
    {
        SGX_ERROR_INVALID_ATTRIBUTE,
        "Enclave was not authorized.",
        NULL
    },
    {
        SGX_ERROR_ENCLAVE_FILE_ACCESS,
        "Can't open enclave file.",
        NULL
    },
    {
        SGX_ERROR_MEMORY_MAP_FAILURE,
        "Failed to reserve memory for the enclave.",
        NULL
    },
};

/* Check error conditions for loading enclave */
void print_error_message(sgx_status_t ret)
{
    size_t idx = 0;
    size_t ttl = sizeof sgx_errlist/sizeof sgx_errlist[0];

    for (idx = 0; idx < ttl; idx++) {
        if(ret == sgx_errlist[idx].err) {
            if(NULL != sgx_errlist[idx].sug)
                printf("Info: %s\n", sgx_errlist[idx].sug);
            printf("Error: %s\n", sgx_errlist[idx].msg);
            break;
        }
    }
    
    if (idx == ttl)
    	printf("Error code is 0x%X. Please refer to the \"Intel SGX SDK Developer Reference\" for more details.\n", ret);
}

// Initialize the enclave:
int initialize_enclave(void)
{
    sgx_status_t ret = SGX_ERROR_UNEXPECTED;
    
    /* Call sgx_create_enclave to initialize an enclave instance */
    /* Debug Support: set 2nd parameter to 1 */
    ret = sgx_create_enclave(ENCLAVE_FILENAME, SGX_DEBUG_FLAG, NULL, NULL, &global_eid, NULL);
    if (ret != SGX_SUCCESS) {
        print_error_message(ret);
        return -1;
    }

    return 0;
}



/* OCalls implementations */

// Simple printf for debug
void ocall_print_string(const char *str)
{
    printf("%s", str);
}



/* Helper functions */

// Returns the string with the content the file
char* read_file_to_string(const char* filename) {

    FILE *f = fopen(filename, "r");
    if (f == NULL) {
        printf("Error: Could not open %s\n", filename);
        return NULL;
    }

    // Determine file size
    fseek(f, 0, SEEK_END); // SEEK_END is relative to the end-of-file
    long fsize = ftell(f);
    fseek(f, 0, SEEK_SET); // SEEK_SET is relative to the start-of-file

    printf("[App] The size of the file %s is %ld bytes\n", filename,fsize);

    // Allocate memory (fsize + 1 for the null terminator)
    char *string = (char *)malloc(fsize + 1);
    if (string == NULL) {
        fclose(f);
        return NULL;
    }

    // Read and close
    fread(string, fsize, 1, f);
    fclose(f);
    string[fsize] = '\0'; 

    printf("[App] Total memory allocated (including null terminator): %ld bytes\n", fsize + 1);

    return string;
}

// Parses the JSON and sends the array to the Enclave
void parse_and_send_schedule(sgx_enclave_id_t eid, const char* json_string) {

    // Safety check
    if (json_string == NULL) {
        printf("[App Error] Failed to load JSON\n");
        return;
    }

    cJSON *json = cJSON_Parse(json_string);

    if (json == NULL) {
        printf("[App Error] Failed to parse JSON\n");
        return;
    }
}



/* Application entry */

int SGX_CDECL main(int argc, char *argv[])
{
    // To avoid compilation errors
    (void)(argc);
    (void)(argv);

    /* Initialize the enclave */
    if(initialize_enclave() < 0){
        printf("[App Error] Unable to start enclave");
        printf("Enter a character before exit ...\n");
        getchar();
        return -1; 
    }

    // Memory address of the files content
    char* json_data = read_file_to_string("schedules.json");
    
    parse_and_send_schedule(global_eid, json_data);

    /* Destroy the enclave */
    sgx_destroy_enclave(global_eid);
    
    printf("Info: Enclave successfully returned.\n");

    printf("Enter a character before exit ...\n");
    getchar();
    return 0;
}